spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_store
    username: postgres
    password: postgres
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
          temperature: 0.3
      embedding:
        options:
          model: text-embedding-ada-002

carina:
  vectorSearch:
    topK: 4
    similarityThreshold: 0.75